spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/books?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev


server:
  port: 8080
#logging:
#  config: classpath:logback-custom.xml



